### ISSUE TITLE
Fix: Option in configuration to fix nodes in place after dragging them (Similar to the default behavior in Neo4j Browser's visualization)

### ISSUE THREAD

**Issue by baibhavbista** [neo4j-contrib/neovis.js#146] opened 2020-11-30 07:10 UTC
Neo4j browser has this feature where after dragging a node somewhere in the canvas, it is fixed there (until it is dragged again). Is there already a way to do this in neovis.js?

If not, it is quite a simple addition. I added this functionality by adding listeners for the events 'dragStart' and 'dragEnd' after this line: https://github.com/neo4j-contrib/neovis.js/blob/master/src/neovis.js#L460  (in the `onCompleted` function after handling clicks)
```js
if(this._config.fix_nodes_in_place_on_drag){
  this._network.on('dragStart', function(params) {
    if (params.nodes.length > 0) {
      let nodeId = this.getNodeAt(params.pointer.DOM);
      neoVis._data.nodes.update({id: nodeId, fixed: {x: false, y: false}});
    }
  });
  this._network.on('dragEnd', function (params) {
    if (params.nodes.length > 0) {
      let nodeId = this.getNodeAt(params.pointer.DOM);
      neoVis._data.nodes.update({id: nodeId, fixed: {x: true, y: true}});
    }
  });
}
```

Note: `fix_nodes_in_place_on_drag` is a bool that has to be added to the configuration object

Since this is default behavior in Neo4j browser, and most people who use neovis.js have experience with the browser, I think this is a good configuration to have. Do let me know if you would like me to submit a Pull request for the same.

**Comment by thebestnom** [comment] 2020-11-30 07:36
Im pretty sure this is not a bug and the default vis behavior.
Im currently working first on https://github.com/neo4j-contrib/neovis.js/issues/144 which will allow to add any vis configuration by default so any additions to currently available config will be lost

But as I can see here https://github.com/almende/vis/issues/315 you did the right way so if you want to open a PR which does that Im ok with merging that

**Comment by baibhavbista** [comment] 2020-11-30 08:06
@thebestnom Oh sorry. I did not mean it was a bug. I meant that, due to it being the default in Neo4j browser, people might want it here too.
#144 sounds like a big structural change. In that case, I think I will wait after that change is done. Will submit the pull request then if it is required.

**Comment by thebestnom** [comment] 2021-02-07 22:27
published 2.0.0 alpha if you want to check it out, doc are out of date, but the .d.ts is uptodate

**Comment by ItamarSoffer** [comment] 2021-11-05 20:29
Hi, I have tried to implant this code and it didn't work. I dragged all the objects and they still return. Also I added to the config the  `fix_nodes_in_place_on_drag : true`

Any ideas why?

**Comment by thebestnom** [comment] 2021-11-06 16:04
You should read the full conversation and not just try random code from issues 😅
Also on 2.x this library took a kind of a different approach than trying to mimick neo4j desktop so this is out of scope for this library 😅

**Closed** 2021-11-07 12:41 UTC

**Comment by samiib** [comment] 2022-02-17 00:25
> Neo4j browser has this feature where after dragging a node somewhere in the canvas, it is fixed there (until it is dragged again). Is there already a way to do this in neovis.js?
> 
> If not, it is quite a simple addition. I added this functionality by adding listeners for the events 'dragStart' and 'dragEnd' after this line: https://github.com/neo4j-contrib/neovis.js/blob/master/src/neovis.js#L460 (in the `onCompleted` function after handling clicks)
> 
> ```js
> if(this._config.fix_nodes_in_place_on_drag){
>   this._network.on('dragStart', function(params) {
>     if (params.nodes.length > 0) {
>       let nodeId = this.getNodeAt(params.pointer.DOM);
>       neoVis._data.nodes.update({id: nodeId, fixed: {x: false, y: false}});
>     }
>   });
>   this._network.on('dragEnd', function (params) {
>     if (params.nodes.length > 0) {
>       let nodeId = this.getNodeAt(params.pointer.DOM);
>       neoVis._data.nodes.update({id: nodeId, fixed: {x: true, y: true}});
>     }
>   });
> }
> ```
> 
> Note: `fix_nodes_in_place_on_drag` is a bool that has to be added to the configuration object
> 
> Since this is default behavior in Neo4j browser, and most people who use neovis.js have experience with the browser, I think this is a good configuration to have. Do let me know if you would like me to submit a Pull request for the same.

This was perfect thankyou. Worked well for me. :)
